export interface Notification {
  title: string;
  body: string;
  for: 'transporter' | 'customer';
  type: NotificationTypeEnum;
  data: any;
}

export enum NotificationTypeEnum {
  DELIVERY_OFFER_NEW_CORRESPONDING_REQUEST = 'DELIVERY_OFFER_NEW_CORRESPONDING_REQUEST',
  DELIVERY_OFFER_EXPIRED = 'DELIVERY_OFFER_EXPIRED',
  DELIVERY_REQUEST_NEW_CORRESPONDING_OFFER = 'DELIVERY_REQUEST_NEW_CORRESPONDING_OFFER',
  DELIVERY_REQUEST_EXPIRED = 'DELIVERY_REQUEST_EXPIRED',
  BOOKING_EXPIRED = 'BOOKING_EXPIRED',
  BOOKING_CANCELED = 'BOOKING_CANCELED',
  BOOKING_CLAIMED = 'BOOKING_CLAIMED',
  BOOKING_ACCEPTED = 'BOOKING_ACCEPTED',
  BOOKING_REFUSED = 'BOOKING_REFUSED',
  BOOKING_PAID = 'BOOKING_PAID',
  BOOKING_RECEIVED_BY_TRANSPORTER = 'BOOKING_RECEIVED_BY_TRANSPORTER',
  BOOKING_RECEIVED_BY_DEPARTURE_RELAY_POINT = 'BOOKING_RECEIVED_BY_DEPARTURE_RELAY_POINT',
  BOOKING_DELIVERED_BY_DEPARTURE_RELAY_POINT = 'BOOKING_DELIVERED_BY_DEPARTURE_RELAY_POINT',
  BOOKING_DELIVERED_BY_TRANSPORTER = 'BOOKING_DELIVERED_BY_TRANSPORTER',
  BOOKING_RECEIVED_BY_ARRIVAL_RELAY_POINT = 'BOOKING_RECEIVED_BY_ARRIVAL_RELAY_POINT',
  BOOKING_DELIVERED_BY_ARRIVAL_RELAY_POINT = 'BOOKING_DELIVERED_BY_ARRIVAL_RELAY_POINT'
}
