export interface INotification {
  id: string;
  userId: string;
  event: NotificationEvent;
  resource: NotificationResource;
  date: number;
  seen: boolean;
}

export interface NotificationResource {
  id: string;
  type: ResourceType;
}

export enum ResourceType {
  USER = 'USER',
  DELIVERY_OFFER = 'DELIVERY_OFFER',
  DELIVERY_REQUEST = 'DELIVERY_REQUEST',
  BOOKING = 'BOOKING'
}

export enum NotificationEvent {

  // --USER
  USER_REGISTRATION = "USER_REGISTRATION",
  USER_CREATION = "USER_CREATION",
  USER_ACCOUNT_ENABLED = "USER_ACCOUNT_ENABLED",
  USER_ACCOUNT_DISABLED = "USER_ACCOUNT_DISABLED",
  USER_IDENTITY_VERIFICATION_ACCEPTED = "USER_IDENTITY_VERIFICATION_ACCEPTED",
  USER_IDENTITY_VERIFICATION_REFUSED = "USER_IDENTITY_VERIFICATION_REFUSED",
  USER_BANK_ACCOUNT_VERIFICATION_ACCEPTED = "USER_BANK_ACCOUNT_VERIFICATION_ACCEPTED",
  USER_BANK_ACCOUNT_VERIFICATION_REFUSED = "USER_BANK_ACCOUNT_VERIFICATION_REFUSED",
  USER_IDENTITY_VERIFICATION_UPDATED = "USER_IDENTITY_VERIFICATION_UPDATED",
  USER_BANK_ACCOUNT_VERIFICATION_UPDATED = "USER_BANK_ACCOUNT_VERIFICATION_UPDATED",

  // --DELIVERY_OFFER
  DELIVERY_OFFER_CREATION = "DELIVERY_OFFER_CREATION",
  DELIVERY_OFFER_EXPIRATION = "DELIVERY_OFFER_EXPIRATION",
  DELIVERY_OFFER_MATCHING = "DELIVERY_OFFER_MATCHING",

  // --DELIVERY_REQUEST
  DELIVERY_REQUEST_PARCEL_CREATION = "DELIVERY_REQUEST_PARCEL_CREATION",
  DELIVERY_REQUEST_PRESCRIPTION_CREATION = "DELIVERY_REQUEST_PRESCRIPTION_CREATION",
  DELIVERY_REQUEST_PRODUCT_CREATION = "DELIVERY_REQUEST_PRODUCT_CREATION",

  DELIVERY_REQUEST_EXPIRATION_PARCEL = "DELIVERY_REQUEST_EXPIRATION_PARCEL",
  DELIVERY_REQUEST_EXPIRATION_PRESCRIPTION = "DELIVERY_REQUEST_EXPIRATION_PRESCRIPTION",
  DELIVERY_REQUEST_EXPIRATION_PRODUCT = "DELIVERY_REQUEST_EXPIRATION_PRODUCT",

  DELIVERY_REQUEST_MATCHING_PARCEL = "DELIVERY_REQUEST_MATCHING_PARCEL",
  DELIVERY_REQUEST_MATCHING_PRESCRIPTION = "DELIVERY_REQUEST_MATCHING_PRESCRIPTION",
  DELIVERY_REQUEST_MATCHING_PRODUCT = "DELIVERY_REQUEST_MATCHING_PRODUCT",

  // --BOOKING
  BOOKING_CREATION_PARCEL = "BOOKING_CREATION_PARCEL",
  BOOKING_CREATION_PRESCRIPTION = "BOOKING_CREATION_PRESCRIPTION",
  BOOKING_CREATION_PRODUCT = "BOOKING_CREATION_PRODUCT",

  BOOKING_CANCELED_PARCEL = "BOOKING_CANCELED_PARCEL",
  BOOKING_CANCELED_PRESCRIPTION = "BOOKING_CANCELED_PRESCRIPTION",
  BOOKING_CANCELED_PRODUCT = "BOOKING_CANCELED_PRODUCT",

  BOOKING_REJECTED_PARCEL = "BOOKING_REJECTED_PARCEL",
  BOOKING_REJECTED_PRESCRIPTION = "BOOKING_REJECTED_PRESCRIPTION",
  BOOKING_REJECTED_PRODUCT = "BOOKING_REJECTED_PRODUCT",

  BOOKING_PENDING_PAYMENT_PARCEL = "BOOKING_PENDING_PAYMENT_PARCEL",
  BOOKING_PENDING_PAYMENT_PRODUCT = "BOOKING_PENDING_PAYMENT_PRODUCT",

  BOOKING_PAID_AWAITING_PICKUP_PARCEL = "BOOKING_PAID_AWAITING_PICKUP_PARCEL",

  BOOKING_PAYLOAD_PICKED_UP_BY_DEPARTURE_RELAY_POINT_PARCEL = "BOOKING_PAYLOAD_PICKED_UP_BY_DEPARTURE_RELAY_POINT_PARCEL",

  BOOKING_IN_TRANSIT_PARCEL = "BOOKING_IN_TRANSIT_PARCEL",
  BOOKING_IN_TRANSIT_PRESCRIPTION = "BOOKING_IN_TRANSIT_PRESCRIPTION",
  BOOKING_IN_TRANSIT_PRODUCT = "BOOKING_IN_TRANSIT_PRODUCT",

  BOOKING_PAYLOAD_PICKED_UP_BY_ARRIVAL_RELAY_POINT_PARCEL = "BOOKING_PAYLOAD_PICKED_UP_BY_ARRIVAL_RELAY_POINT_PARCEL",
  BOOKING_PAYLOAD_PICKED_UP_BY_ARRIVAL_RELAY_POINT_PRODUCT = "BOOKING_PAYLOAD_PICKED_UP_BY_ARRIVAL_RELAY_POINT_PRODUCT",

  BOOKING_DELIVERED_PARCEL = "BOOKING_DELIVERED_PARCEL",
  BOOKING_DELIVERED_PRESCRIPTION = "BOOKING_DELIVERED_PRESCRIPTION",
  BOOKING_DELIVERED_PRODUCT = "BOOKING_DELIVERED_PRODUCT",

  BOOKING_CLAIMED_PARCEL = "BOOKING_CLAIMED_PARCEL",
  BOOKING_CLAIMED_PRESCRIPTION = "BOOKING_CLAIMED_PRESCRIPTION",
  BOOKING_CLAIMED_PRODUCT = "BOOKING_CLAIMED_PRODUCT",

  BOOKING_COMPLETED_PARCEL = "BOOKING_COMPLETED_PARCEL",
  BOOKING_COMPLETED_PRESCRIPTION = "BOOKING_COMPLETED_PRESCRIPTION",
  BOOKING_COMPLETED_PRODUCT = "BOOKING_COMPLETED_PRODUCT",

  BOOKING_EXPIRED_PARCEL = "BOOKING_EXPIRED_PARCEL",
  BOOKING_EXPIRED_PRESCRIPTION = "BOOKING_EXPIRED_PRESCRIPTION",
  BOOKING_EXPIRED_PRODUCT = "BOOKING_EXPIRED_PRODUCT",

  BOOKING_PENDING_CUSTOMER_APPROVAL_PRESCRIPTION = "BOOKING_PENDING_CUSTOMER_APPROVAL_PRESCRIPTION",

  BOOKING_PAID_PENDING_PURCHASE_PRODUCT = "BOOKING_PAID_PENDING_PURCHASE_PRODUCT",

  BOOKING_PENDING_PURCHASE_PRESCRIPTION = "BOOKING_PENDING_PURCHASE_PRESCRIPTION"
}
